name:                movie-recon
version:             0.1.0.0
github:              "githubuser/movie-recon"
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/movie-recon#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- text
- mtl
- transformers
- HTTP
- bytestring
- utf8-string
- aeson
- vector
- directory
- persistent
- persistent-template
- persistent-sqlite
- esqueleto
- exceptions
- temporary
- lens
- time
- cmdargs
- regex-compat
- either
- monad-logger
- resourcet
- interpolatedstring-perl6


library:
  source-dirs: src

executables:
  movie-recon-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - movie-recon

tests:
  movie-recon-test:
    main:                Driver.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - movie-recon
    - HUnit
    - QuickCheck
    - tasty
    - tasty-hunit
    - tasty-hunit-adapter
    - tasty-discover >= 4.2.1
    - random
    - raw-strings-qq
